language: python
python:
  - "3.6"

services:
  - postgresql

# before_install:
#   - export DATABASE_URL_TEST = "postgresql://postgres@localhost/shoppinglist_test"


# command to install dependencies
install:
  - pip install coverage
  - pip install -r requirements.txt
  - pip install coveralls --quiet


before_script:
  - psql -c 'create database shoppinglist_test;' -U postgres

# command to run tests
script: nosetests

after_success: coveralls
