
language: python
python:
  - "3.6"

services:
  - postgresql

before_install:
  - export DATABASE_URL_TEST="postgresql://postgres@localhost/shoppinglist_test"
  - export APP_SETTINGS="app.config.TestingConfig"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls --quiet


before_script:
  - psql -c 'create database shoppinglist_test;' -U postgres

# command to run tests
script: coverage run --source=app ./manage.py test
after_success: coveralls