language: python
python:
  - "3.6"

services:
  - postgresql


# command to install dependencies
install:
  - pip install coverage
  - pip install -r requirements.txt
  - pip install coveralls --quiet


before_script:
  - psql -c "CREATE ROLE kisakye PASSWORD 'kisakye6' CREATEDB CREATEROLE INHERIT LOGIN;" -U postgres
  - psql -c "create database shoppinglist_db;" -U postgres
  - psql -c "grant all privileges on database shoppinglist_db to kisakye;" -U postgres
  - python manage.py db init
  - python manage.py db migrate
  - python manage.py db upgrade

# command to run tests
script: nosetests --with-coverage --cover-package=app

after_success: coveralls
