"""empty message

Revision ID: 2f0f538e4494
Revises: 75fa37b1749f
Create Date: 2017-09-25 20:29:37.859095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f0f538e4494'
down_revision = '75fa37b1749f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('shoppinglists', sa.Column('owner', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shoppinglists', 'users', ['owner'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shoppinglists', type_='foreignkey')
    op.drop_column('shoppinglists', 'owner')
    op.drop_table('users')
    # ### end Alembic commands ###
