"""empty message

Revision ID: 85881c4630e2
Revises: ac92de84b8be
Create Date: 2017-11-22 19:13:46.722588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85881c4630e2'
down_revision = 'ac92de84b8be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listitem', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('listitem', sa.Column('date_modified', sa.DateTime(), nullable=True))
    op.add_column('shoppinglists', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('shoppinglists', sa.Column('date_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shoppinglists', 'date_modified')
    op.drop_column('shoppinglists', 'date_created')
    op.drop_column('listitem', 'date_modified')
    op.drop_column('listitem', 'date_created')
    # ### end Alembic commands ###
