"""empty message

Revision ID: 8b878b809ed0
Revises: 85881c4630e2
Create Date: 2017-12-21 23:31:56.027665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b878b809ed0'
down_revision = '85881c4630e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'listitem', ['name'])
    op.create_unique_constraint(None, 'shoppinglists', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shoppinglists', type_='unique')
    op.drop_constraint(None, 'listitem', type_='unique')
    # ### end Alembic commands ###
